var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                             xxxxxxxxxxxxxxxxxxxxxxxxxxx                        ",
   "                             x                       x                          ",
   "                             x                       x                          ",
   "                             x                       x                          ",
   "                             x         xx            xx                         ",
   "                             x   xxx   xxx           xx                         ",
   "                             x              xxx      xx                         ",
   "                             x                               x           xxxxx  ",
   "  xxxx                       xxxxx  x!!!!!!!!!!x            xx             !!x  ",
   "  x                                 x!!!!!!!!!!x         xxxxx             !!x  ",
   "  x       l                         xxxxxxxxxxxx     xx    !xx             !!x  ",
   "  x       x    x                xxxxxxxxxxxxxxxx          l!xx       o     !!x  ",
   "  x  @   xx!!!!xx               xxxxxxxxxxxxxxxxx        xx!xx             !!x  ",
   "  xxxxxxxxx!!!!xxxIIIIIIIIIIIIIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "          xxxxxx                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                   ",
   "                                             x                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      ",
   "                                             x                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      ",
   "                                             x                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      ",
   "                                             x                                x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      ",
   "                                             x      III                       x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!      ",
   "                                             x             xxxx               x        vvvvvvvvvvvvvvvvvvvvv      ",
   "                                             xxxx            v                x                                   ",
   "                                                                  IIII        x                                   ",
   "                                                 xxx                          x                                   ",
   "                                                                           xxxx                                   ",
   "                                                                   xxx                                            ",
   "                                                       xxx    l                                                   ",
   " xxxxxxx                                                      I        xx                                         ",
   " x                                                xxxx                                                            ",
   " x@                                       xxxx                              xxxx                                  ",
   " xx                                                                                                               ",
   " xxx   xxx     IIIIIIII!!            xxx                                                                   x      ",
   " xxx   xxx    IIIIIIIII!!                  xx                                                            !!x      ",
   " xxxx!!!!!!!!IIIIIIIIII!!                                                                                !!x      ",
   " xxxxx!!!!!!!IIIIIIIIII!!              xx                                                                !!x      ",
   " xxxxxx!!!!!!IIIIIIIIII!!xx          xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                      !!x      ",
   " xxxxxx!!!!!!IIIIIIIIII!!x          xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                 o  !!x      ",
   " xxxxxxxxxxxxIIIIIIIIII!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxIIIxxxxxxxxxxxxxxxxxx        ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                 xxx                                                          ",
   "                                                   x                                                          ",
   "                                                   x                                                          ",
   "                                                   x                                                          ",
   "                                                   x                                                          ",
   "                           !                       x                                                          ",
   "                           !                       x                                                          ",
   "                           !            III        x                                                          ",
   "                           !                = !    x                         v                                ",
   "                           !    III           !    x                                                          ",
   "                           !                  !    x                                                          ",
   "                           !           III    !    x      xxxxxx                                              ",
   "                           !l      =          !    x      x                                                   ",
   "                           !xxxxxxx   xxxxxxxxxx   x      x                           v                       ",
   "                                     x             x      x                                   v         v  x  ",
   "                                    x              x     lx            IIII                                x  ",
   "                    xxxxxxx        x      xxxxxxxxxx      x                     IIII                       x  ",
   "                    !!v           x                       xxx   xxx                                        x  ",
   "                    !!        =  xx                             !                       IIII               x  ",
   "                    !!           xx   xx                        !                               IIIII      x  ",
   "                    !!          xxx       xxxx                  !                                          x  ",
   "  xxx               !!l         xxx                     xxxxxxxxx                                          x  ",
   "  x x               xxxx     xxxxxx               xxx                                                    o x  ",
   "  x                 x             x                                                                      xxx  ",
   "  x                 x             x                                                                           ",
   "  x                 x     xx     xx                                                                           ",
   "  x                 x            xx                                                                           ",
   "  x                 x xx         xx                                                                           ",
   "  x                              xx                                                                           ",
   "  x                       xx     !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  x               xxxxx          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  x      @        xxxxx         l!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  ",
   "  xxxxxxxxxxxxxxxxxxxxxIIIIIIIIIIxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                ",
   "                                                                             o  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                 @                                                              ",
   " x     x     x   x  xx   x                                                      ",
   "  x   x x   x    x  x x  x                                                      ",
   "   x x   x x     x  x  x x                                                      ",
   "    x     x      x  x   xx                                                      ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
   ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   " x       xxx     xxxx   xxxx                                                    ",
   " x      x   x    x      x                                                       ",
   " x      x @ x    xxxx   xxxx                                                    ",
   " x      x!!!x       x   x                                              o        ",
   " xxxxx   xxx     xxxx   xxxx                                                    ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
